version: "3.3"

services:
  rishighan:
    image: frishi/rishighan
    container_name: rishighan
    volumes:
      - "./ecosystem.config.json:/ecosystem.config.json"
    external_links: 
      - caddy
    ports:
      - 8999:8999
    networks:
      - main-network

networks:
  main-network:
    external: true
