version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/node:10.16.0"
    steps:
      - checkout
      - run:
          name: Update to latest npm version
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install dependencies
          command: yarn 
      - setup_remote_docker:
          docker_layer_caching: false 
      - run:
          name: Build using `docker-compose`
          command: |
            docker-compose build
      - run:
          name: Login for Docker Hub
          command: | 
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Push to Docker Hub
          command: |
            docker-compose push
      - run: ssh-keyscan $DIGITALOCEAN_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - db:62:b9:ad:c1:08:29:b7:ed:ab:72:66:c5:43:1d:98
      - run:
          name: Deploy to Digital Ocean Droplet
          command: |
            # deploy script 
            bash ./scripts/deploy/deploy.sh -u $DIGITALOCEAN_USERNAME \
                                            -h $DIGITALOCEAN_HOST \
                                            -s $SERVICE_NAME \
                                            -r $REPOSITORY_BASE_URL 