export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';

export const FETCH_DRAFTS_SUCCESS = 'FETCH_DRAFTS_SUCCESS';

export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE';

export const DROP_FILE = 'DROP_FILE';
