export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const CREATE_SERIES_SUCCESS = 'CREATE_SERIES_SUCCESS';
export const CREATE_SERIES_ERROR = 'CREATE_SERIES_ERROR';

export const UPDATE_SERIES_SUCCESS = 'UPDATE_SERIES_SUCCESS';
export const DELETE_SERIES_SUCCESS = 'DELETE_SERIES_SUCCESS';

export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_SERIES_ERROR = 'FETCH_SERIES_ERROR';

export const FIND_SERIES_BY_POSTID_SUCCESS = 'FIND_SERIES_BY_POSTID_SUCCESS';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

export const GET_DIFF_HISTORIES_SUCCESS = 'GET_DIFF_HISTORIES_SUCCESS';

export const GENERIC_POSTS_API_ERROR = 'GENERIC_POSTS_API_ERROR';

export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';

export const FETCH_DRAFTS_SUCCESS = 'FETCH_DRAFTS_SUCCESS';

export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE';